# Generated by Django 5.1 on 2024-08-20 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(default='', max_length=255)),
                ('stock', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, upload_to='product_images/')),
                ('status', models.CharField(choices=[('Bought', 'Bought'), ('Sold', 'Sold')], default='Bought', max_length=6)),
                ('favorite', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
