# Generated by Django 5.1.1 on 2024-09-05 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryimage',
            name='image',
            field=models.ImageField(blank=True, help_text='Image must be under 10MB', max_length=1000, null=True, upload_to='../media/category_images/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, help_text='Image must be under 10MB', max_length=1000, null=True, upload_to='../media/product_images/', verbose_name='image'),
        ),
    ]
