# Generated by Django 5.1.1 on 2024-09-05 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_categoryimage_image_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryimage',
            name='image',
            field=models.ImageField(blank=True, help_text='Image must be under 10MB', max_length=1000, null=True, upload_to='category_images/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, help_text='Image must be under 10MB', max_length=1000, null=True, upload_to='product_images/', verbose_name='image'),
        ),
    ]
